apiVersion: v2
name: node-provider-labeler
description: Set Kubernetes Node metadata from cloud provider IDs
type: application
appVersion: "0.8.0"
version: "0.20.0"
keywords:
  - kubernetes
  - nodes
  - monitoring
home: https://github.com/jossware/node-provider-labeler/
sources:
  - https://github.com/jossware/node-provider-labeler/
maintainers:
  - name: ryane
    email: ryan@jossware.com
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: MIT
