# Default values for node-provider-labeler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- The number of replicas to run
replicaCount: 1

image:
  # -- The image to use in the controller deployment
  repository: ghcr.io/jossware/node-provider-labeler
  # -- The tag of the image
  tag: "v0.7.0"
  # -- The image pull policy
  pullPolicy: IfNotPresent

# -- Optionally define templates for labels and/or annotations. If not defined, the
# chart will create the default label and value
templates: {}
# templates:
#   labels:
#     - key: instance-id
#       value: "{:last}"
#   annotations:
#     - key: aws-region
#       value: "{:first}"

# -- Secrets with credentials to pull images from a private registry
imagePullSecrets: []

# -- Provide a name in place of the default
nameOverride: ""
# -- String to fully override `"node-provider-labeler.fullname"`
fullnameOverride: ""

# -- [Environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/) for the controller container.
extraEnv: []
# - name: SOME_VAR
#   value: 'some value'

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # -- Specifies whether RBAC roles and bindings should be created
  create: true

# -- Annotations to be added to the pods
podAnnotations: {}
# -- Labels to be added to the pods
podLabels: {}

# -- Pod level security context
podSecurityContext:
  {}
  # fsGroup: 2000

# -- Container level security context
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Metrics service type
  type: ClusterIP
  # -- Metrics service port
  port: 8080

# -- Resource limits and requests for the deployment
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Server readiness probe
readinessProbe:
  httpGet:
    # -- HTTP path for readiness probe
    path: /health
    # -- Port for readiness probe
    port: http

# -- Additional volumes to add on the deployment.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts to add to the deployment.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# -- Node selector.
nodeSelector: {}

# -- Tolerations for use with node taints.
tolerations: []

# -- Assign custom affinity rules to the deployment.
affinity: {}
