apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
- namespace.yaml
- base # konvert.kumorilabs.io/chart: ../charts/node-provider-labeler
