{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-provider-labeler.fullname" . }}
  labels:
    {{- include "node-provider-labeler.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-provider-labeler.fullname" . }}
  labels:
    {{- include "node-provider-labeler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-provider-labeler.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-provider-labeler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
