last = { "{:last}" }
first = { "{:first}" }
all = { "{:all}" }
provider = { "{:provider}" }
idx = { ASCII_DIGIT+ }
nth = { "{" ~ idx ~ "}" }
char = { ASCII_ALPHANUMERIC | "." | "_" | "-" | "/" | " " }
label_char = { ASCII_ALPHA | ASCII_DIGIT | "-" | "_" | "."}
annotation = {
    SOI ~
    ((last | first | all | provider | nth | char)+)+ ~
    EOI
}
label = {
    SOI ~
    ((last | first | all | provider | nth | label_char)+)+ ~
    EOI
}
