last = { "{:last}" }
first = { "{:first}" }
all = { "{:all}" }
provider = { "{:provider}" }
url = { "{:url}" }
idx = { ASCII_DIGIT+ }
nth = { "{" ~ idx ~ "}" }
char = { ASCII }
label_char = { ASCII_ALPHA | ASCII_DIGIT | "-" | "_" | "."}
annotation = {
    SOI ~
    ((last | first | all | provider | url | nth | char)+)+ ~
    EOI
}
label = {
    SOI ~
    ((last | first | all | provider | url | nth | label_char)+)+ ~
    EOI
}
