# Source: node-provider-labeler/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-provider-labeler
  labels:
    helm.sh/chart: node-provider-labeler-0.17.0
    app.kubernetes.io/name: node-provider-labeler
    app.kubernetes.io/instance: node-provider-labeler
    app.kubernetes.io/version: "0.7.0"
    app.kubernetes.io/managed-by: konvert
  annotations:
    konvert.kumorilabs.io/generated-by: 'konvert'
    konvert.kumorilabs.io/chart: '../charts/node-provider-labeler'
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
  - update
