apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: 'true'
namespace: node-provider-labeler
resources:
- clusterrole-node-provider-labeler.yaml # konvert.kumorilabs.io/chart: ../charts/node-provider-labeler
- clusterrolebinding-node-provider-labeler.yaml # konvert.kumorilabs.io/chart: ../charts/node-provider-labeler
- deployment-node-provider-labeler.yaml # konvert.kumorilabs.io/chart: ../charts/node-provider-labeler
- service-node-provider-labeler.yaml # konvert.kumorilabs.io/chart: ../charts/node-provider-labeler
- serviceaccount-node-provider-labeler.yaml # konvert.kumorilabs.io/chart: ../charts/node-provider-labeler
