name: Build and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build and Tests - ${{ matrix.platform.build_for }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        platform:
          - build_for: linux/amd64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: node-provider-labeler
            name: node-provider-labeler-linux-x86_64
            command: both

          - build_for: linux/arm64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            bin: node-provider-labeler
            name: node-provider-labeler-linux-aarch64
            command: both

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform.build_for }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
